ciegl: cie::gl::AbsWindow Class Reference
cie::gl::AbsWindow Class Reference abstract
Public Types
using key_callback_function = std::function< void(KeyEnum, KeyEnum, KeyEnum)>
{key, action, modifier}
using mouse_callback_function = std::function< void(Double, Double, KeyEnum, KeyEnum, KeyEnum)>
{x, y, button, action, modifier}
using WindowSize = std::pair< Size, Size >
{width, height}
Public Types inherited from cie::utils::IDObject< class >
typedef TID id_type
Public Member Functions
virtual ~AbsWindow ()
virtual bool update ()
Update all scenes and draw.
virtual void activate ()=0
Make window active.
void setSize (WindowSize size)
void setSize (Size width, Size height)
const std::pair< Size, Size > & getSize () const
double getAspectRatio () const
template<class SceneType , class ... Args>
std::shared_ptr< SceneType > makeScene (Args &&... args)
Construct a new scene and add it to this window.
virtual void removeScene (ScenePtr p_scene)
Attempt to remove a scene from this window.
const scene_container & scenes () const
void beginLoop ()
void endLoop ()
void screenshot (const std::filesystem::path &r_outputPath, Image *p_targetImage=nullptr) const
void setMouseButtonCallback (MouseButtonCallback function)
void setCursorPositionCallback (CursorPositionCallback function)
void setCursorEnterCallback (CursorEnterCallback function)
void setScrollCallback (ScrollCallback function)
void setKeyboardCallback (KeyboardCallback function)
void setWindowResizeCallback (WindowResizeCallback function)
virtual void setName (std::string::const_iterator begin, std::string::const_iterator end) override
Public Member Functions inherited from cie::utils::IDObject< class >
IDObject ()
IDObject (const TID &r_id)
IDObject (IDObject &&r_rhs)=default
IDObject (const IDObject &r_rhs)=default
IDObject & operator= (IDObject &&r_rhs)=default
IDObject & operator= (const IDObject &rhs)=default
void setID (TID id)
const TID getID () const
Public Member Functions inherited from cie::utils::Loggee
Loggee (Logger &r_logger, const std::string &r_instanceName)
~Loggee ()
void log (const std::string &message, size_t messageType=LOG_TYPE_MESSAGE)
void logID (const std::string &message, size_t id, size_t messageType=LOG_TYPE_MESSAGE)
size_t tic ()
void toc (size_t timerID, bool reset=true)
void toc (const std::string &message, size_t timerID, bool reset=true)
LogBlock newBlock (const std::string &r_name)
void separate ()
Public Member Functions inherited from cie::utils::NamedObject
NamedObject (std::string &&r_name)
NamedObject (const std::string &r_name)
NamedObject (NamedObject &&r_rhs)=default
NamedObject (const NamedObject &r_rhs)=default
NamedObject & operator= (NamedObject &&r_rhs)=default
NamedObject & operator= (const NamedObject &r_rhs)=default
const std::string & name () const
void setName (const std::string &r_name)
virtual ~NamedObject ()
Public Member Functions inherited from cie::utils::observer::Subject
Subject ()=default
Subject (const SubjectPtr &copy)
SubjectPtr operator= (const SubjectPtr &copy)
virtual ~Subject ()
void notifyObservers ()
int attachObserver (ObserverPtr observer)
void detachObserver (ObserverPtr observer)
int observerID (ObserverPtr observer)
const std::vector< ObserverPtr > & observers () const
std::shared_ptr< DerivedSubject > as ()
Protected Member Functions
AbsWindow (Size id, const std::string &r_name, Size width, Size height, utils::Logger &r_logger=utils::LoggerSingleton::get())
virtual void addScene (ScenePtr p_scene, bool update=true)
Attempt to add a scene to this window.
virtual void setSizeImpl (WindowSize size)=0
virtual bool updateImpl ()=0
virtual void setWindowName (std::string::const_iterator begin, std::string::const_iterator end)=0
void triggerMouseButtonCallback (KeyEnum key, KeyEnum action, KeyEnum modifier)
void triggerCursorPositionCallback (Double x, Double y)
void triggerCursorEnterCallback (KeyEnum hasEntered)
void triggerScrollCallback (Double xOffset, Double yOffset)
void triggerKeyboardCallback (KeyEnum key, KeyEnum scancode, KeyEnum action, KeyEnum modifier)
void triggerWindowResizeCallback (Size width, Size height)
Protected Member Functions inherited from cie::utils::Loggee
Logger & logger ()
Protected Attributes
std::pair< Size, Size > _size
scene_container _scenes
bool _continueLooping
Protected Attributes inherited from cie::utils::IDObject< class >
TID _id
Protected Attributes inherited from cie::utils::observer::Subject
std::vector< ObserverPtr > _observers
Member Typedef Documentation
key_callback_function
using cie::gl::AbsWindow::key_callback_function = std::function<void(KeyEnum,KeyEnum,KeyEnum)>
{key, action, modifier}
mouse_callback_function
using cie::gl::AbsWindow::mouse_callback_function = std::function<void(Double,Double,KeyEnum,KeyEnum,KeyEnum)>
{x, y, button, action, modifier}
WindowSize
using cie::gl::AbsWindow::WindowSize = std::pair<Size,Size>
{width, height}
Constructor & Destructor Documentation
~AbsWindow()
virtual cie::gl::AbsWindow::~AbsWindow () virtual
AbsWindow()
cie::gl::AbsWindow::AbsWindow (Size id, const std::string & r_name, Size width, Size height, utils::Logger & r_logger = utils::LoggerSingleton::get()) protected
Member Function Documentation
activate()
virtual void cie::gl::AbsWindow::activate () pure virtual
Make window active.
Implemented in cie::gl::GLFWWindow.
addScene()
virtual void cie::gl::AbsWindow::addScene (ScenePtr p_scene, bool update = true) protected virtual
Attempt to add a scene to this window.
beginLoop()
void cie::gl::AbsWindow::beginLoop ()
endLoop()
void cie::gl::AbsWindow::endLoop ()
getAspectRatio()
double cie::gl::AbsWindow::getAspectRatio () const
getSize()
const std::pair<Size,Size>& cie::gl::AbsWindow::getSize () const
makeScene()
template<class SceneType , class ... Args> std::shared_ptr<SceneType> cie::gl::AbsWindow::makeScene (Args &&... args)
Construct a new scene and add it to this window.
removeScene()
virtual void cie::gl::AbsWindow::removeScene (ScenePtr p_scene) virtual
Attempt to remove a scene from this window.
scenes()
const scene_container& cie::gl::AbsWindow::scenes () const
screenshot()
void cie::gl::AbsWindow::screenshot (const std::filesystem::path & r_outputPath, Image * p_targetImage = nullptr) const
Copy window data into an RGB image and write it to disk
Parameters
r_outputPath relative or full path of the new image file
p_targetImage preallocated image. If none is given, allocation is performed internally
setCursorEnterCallback()
void cie::gl::AbsWindow::setCursorEnterCallback (CursorEnterCallback function)
setCursorPositionCallback()
void cie::gl::AbsWindow::setCursorPositionCallback (CursorPositionCallback function)
setKeyboardCallback()
void cie::gl::AbsWindow::setKeyboardCallback (KeyboardCallback function)
setMouseButtonCallback()
void cie::gl::AbsWindow::setMouseButtonCallback (MouseButtonCallback function)
setName()
virtual void cie::gl::AbsWindow::setName (std::string::const_iterator begin, std::string::const_iterator end) override virtual
Reimplemented from cie::utils::NamedObject.
setScrollCallback()
void cie::gl::AbsWindow::setScrollCallback (ScrollCallback function)
setSize() [1/2]
void cie::gl::AbsWindow::setSize (Size width, Size height)
setSize() [2/2]
void cie::gl::AbsWindow::setSize (WindowSize size)
setSizeImpl()
virtual void cie::gl::AbsWindow::setSizeImpl (WindowSize size) protected pure virtual
Implemented in cie::gl::GLFWWindow.
setWindowName()
virtual void cie::gl::AbsWindow::setWindowName (std::string::const_iterator begin, std::string::const_iterator end) protected pure virtual
Implemented in cie::gl::GLFWWindow.
setWindowResizeCallback()
void cie::gl::AbsWindow::setWindowResizeCallback (WindowResizeCallback function)
triggerCursorEnterCallback()
void cie::gl::AbsWindow::triggerCursorEnterCallback (KeyEnum hasEntered) protected
triggerCursorPositionCallback()
void cie::gl::AbsWindow::triggerCursorPositionCallback (Double x, Double y) protected
triggerKeyboardCallback()
void cie::gl::AbsWindow::triggerKeyboardCallback (KeyEnum key, KeyEnum scancode, KeyEnum action, KeyEnum modifier) protected
triggerMouseButtonCallback()
void cie::gl::AbsWindow::triggerMouseButtonCallback (KeyEnum key, KeyEnum action, KeyEnum modifier) protected
triggerScrollCallback()
void cie::gl::AbsWindow::triggerScrollCallback (Double xOffset, Double yOffset) protected
triggerWindowResizeCallback()
void cie::gl::AbsWindow::triggerWindowResizeCallback (Size width, Size height) protected
update()
virtual bool cie::gl::AbsWindow::update () virtual
Update all scenes and draw.
Referenced by modules.glvisuals.linevisual.LineVisual::highlightMarkers(), modules.glvisuals.markervisual.MarkerVisual::highlightMarkers(), modules.lighting.timedlight.TimedSpotLight::on_timer(), modules.glmesh.meshvisual.TriangleMeshVisual::updateLight(), modules.glmesh.meshvisual.MeshVisual::updateLight(), and modules.glmesh.meshvisual.MeshVisual::updateMesh().
updateImpl()
virtual bool cie::gl::AbsWindow::updateImpl () protected pure virtual
Implemented in cie::gl::GLFWWindow.
Member Data Documentation
_continueLooping
bool cie::gl::AbsWindow::_continueLooping protected
_scenes
scene_container cie::gl::AbsWindow::_scenes protected
_size
std::pair<Size,Size> cie::gl::AbsWindow::_size protected
The documentation for this class was generated from the following file:
AbsWindow.hpp