ciegl: cie::gl::Scene Class Reference
cie::gl::Scene Class Reference abstract
Public Types
using camera_container = std::list< CameraPtr >
using uniform_container = std::list< GLUniformPtr >
using texture_container = std::list< TexturePtr >
Public Types inherited from cie::utils::IDObject< class >
typedef TID id_type
Public Member Functions
Scene (const std::string &r_name, Shader::SharedPointer p_vertexShader, Shader::SharedPointer p_geometryShader, Shader::SharedPointer p_fragmentShader, utils::Logger &r_logger=utils::LoggerSingleton::get(), VertexBuffer::SharedPointer p_vertexBuffer=nullptr, ElementBuffer::SharedPointer p_elementBuffer=nullptr)
~Scene ()
virtual bool update ()
void activate (bool log=true)
bool isActive () const
Check whether this scene is active.
template<class CameraType , class ... Args>
CameraPtr makeCamera (Args &&... args)
Create a new camera and add it to this Scene.
void addCamera (CameraPtr p_camera)
Add a camera to this Scene.
void removeCamera (CameraPtr p_camera)
Remove camera from this Scene.
const camera_container & cameras () const
CameraPtr camera (Size index=0)
virtual Scene & setVertexShader (Shader::SharedPointer p_vertexShader)
virtual Scene & setGeometryShader (Shader::SharedPointer p_geometryShader)
virtual Scene & setFragmentShader (Shader::SharedPointer p_fragmentShader)
const Shader::SharedPointer & vertexShader () const
const Shader::SharedPointer & geometryShader () const
const Shader::SharedPointer & fragmentShader () const
Scene & setBufferManager (BufferManager::SharedPointer p_bufferManager)
virtual const BufferManager::SharedPointer & bufferManager () const
const uniform_container & uniforms () const
const texture_container & textures () const
void bindUniform (const std::string &r_name, const glm::mat4 &r_uniform)
Bind a 4x4 float matrix to a uniform with the specified name.
void bindUniform (const std::string &r_name, const glm::dvec3 &r_uniform)
Bind a 3D double vector to a uniform with the specified name.
void bindUniform (const std::string &r_name, const glm::vec3 &r_uniform)
Bind a 3D float vector to a uniform with the specified name.
void bindUniform (const std::string &r_name, const GLfloat &r_uniform)
Bind a float scalar to a uniform with the specified name.
template<class ... Args>
void loadTexture (const std::string &r_name, Args &&... args)
Load data to a texture.
Public Member Functions inherited from cie::utils::Loggee
Loggee (Logger &r_logger, const std::string &r_instanceName)
~Loggee ()
void log (const std::string &message, size_t messageType=LOG_TYPE_MESSAGE)
void logID (const std::string &message, size_t id, size_t messageType=LOG_TYPE_MESSAGE)
size_t tic ()
void toc (size_t timerID, bool reset=true)
void toc (const std::string &message, size_t timerID, bool reset=true)
LogBlock newBlock (const std::string &r_name)
void separate ()
Public Member Functions inherited from cie::utils::NamedObject
NamedObject (std::string &&r_name)
NamedObject (const std::string &r_name)
NamedObject (NamedObject &&r_rhs)=default
NamedObject (const NamedObject &r_rhs)=default
NamedObject & operator= (NamedObject &&r_rhs)=default
NamedObject & operator= (const NamedObject &r_rhs)=default
const std::string & name () const
void setName (const std::string &r_name)
virtual void setName (std::string::const_iterator begin, std::string::const_iterator end)
virtual ~NamedObject ()
Public Member Functions inherited from cie::utils::IDObject< class >
IDObject ()
IDObject (const TID &r_id)
IDObject (IDObject &&r_rhs)=default
IDObject (const IDObject &r_rhs)=default
IDObject & operator= (IDObject &&r_rhs)=default
IDObject & operator= (const IDObject &rhs)=default
void setID (TID id)
const TID getID () const
Protected Member Functions
virtual bool update_impl ()=0
Implementation-specific drawing.
Protected Member Functions inherited from cie::utils::Loggee
Logger & logger ()
Protected Attributes
camera_container _cameras
Shader::SharedPointer _p_vertexShader
Shader::SharedPointer _p_geometryShader
Shader::SharedPointer _p_fragmentShader
BufferManager::SharedPointer _p_bufferManager
uniform_container _uniforms
texture_container _textures
GLuint _vaoID
Protected Attributes inherited from cie::utils::IDObject< class >
TID _id
Static Protected Attributes
static Size _activeSceneID
Member Typedef Documentation
camera_container
using cie::gl::Scene::camera_container = std::list<CameraPtr>
texture_container
using cie::gl::Scene::texture_container = std::list<TexturePtr>
uniform_container
using cie::gl::Scene::uniform_container = std::list<GLUniformPtr>
Constructor & Destructor Documentation
Scene()
cie::gl::Scene::Scene (const std::string & r_name, Shader::SharedPointer p_vertexShader, Shader::SharedPointer p_geometryShader, Shader::SharedPointer p_fragmentShader, utils::Logger & r_logger = utils::LoggerSingleton::get(), VertexBuffer::SharedPointer p_vertexBuffer = nullptr, ElementBuffer::SharedPointer p_elementBuffer = nullptr)
Create new GL program, collect shaders, link program, create a new vertex array object, and activate the program.
Note
the scene must be constructed with no bound buffers, but will bind them during construction. New buffers are generated if none are supplied.
~Scene()
cie::gl::Scene::~Scene ()
Member Function Documentation
activate()
void cie::gl::Scene::activate (bool log = true)
Set this scene as active -> calls glUseProgram and binds the vertex array object
addCamera()
void cie::gl::Scene::addCamera (CameraPtr p_camera)
Add a camera to this Scene.
bindUniform() [1/4]
void cie::gl::Scene::bindUniform (const std::string & r_name, const GLfloat & r_uniform)
Bind a float scalar to a uniform with the specified name.
bindUniform() [2/4]
void cie::gl::Scene::bindUniform (const std::string & r_name, const glm::dvec3 & r_uniform)
Bind a 3D double vector to a uniform with the specified name.
bindUniform() [3/4]
void cie::gl::Scene::bindUniform (const std::string & r_name, const glm::mat4 & r_uniform)
Bind a 4x4 float matrix to a uniform with the specified name.
bindUniform() [4/4]
void cie::gl::Scene::bindUniform (const std::string & r_name, const glm::vec3 & r_uniform)
Bind a 3D float vector to a uniform with the specified name.
bufferManager()
virtual const BufferManager::SharedPointer& cie::gl::Scene::bufferManager () const virtual
camera()
CameraPtr cie::gl::Scene::camera (Size index = 0)
Referenced by modules.glmesh.meshvisual.MeshVisual::updateLight().
cameras()
const camera_container& cie::gl::Scene::cameras () const
fragmentShader()
const Shader::SharedPointer& cie::gl::Scene::fragmentShader () const
geometryShader()
const Shader::SharedPointer& cie::gl::Scene::geometryShader () const
isActive()
bool cie::gl::Scene::isActive () const
Check whether this scene is active.
loadTexture()
template<class ... Args> void cie::gl::Scene::loadTexture (const std::string & r_name, Args &&... args)
Load data to a texture.
makeCamera()
template<class CameraType , class ... Args> CameraPtr cie::gl::Scene::makeCamera (Args &&... args)
Create a new camera and add it to this Scene.
removeCamera()
void cie::gl::Scene::removeCamera (CameraPtr p_camera)
Remove camera from this Scene.
setBufferManager()
Scene& cie::gl::Scene::setBufferManager (BufferManager::SharedPointer p_bufferManager)
setFragmentShader()
virtual Scene& cie::gl::Scene::setFragmentShader (Shader::SharedPointer p_fragmentShader) virtual
setGeometryShader()
virtual Scene& cie::gl::Scene::setGeometryShader (Shader::SharedPointer p_geometryShader) virtual
setVertexShader()
virtual Scene& cie::gl::Scene::setVertexShader (Shader::SharedPointer p_vertexShader) virtual
textures()
const texture_container& cie::gl::Scene::textures () const
uniforms()
const uniform_container& cie::gl::Scene::uniforms () const
update()
virtual bool cie::gl::Scene::update () virtual
Update all cameras and uniforms, then call update_impl for all buffers
Referenced by modules.glvisuals.linevisual.LineVisual::highlightMarkers(), modules.glvisuals.markervisual.MarkerVisual::highlightMarkers(), modules.lighting.timedlight.TimedSpotLight::on_timer(), modules.glmesh.meshvisual.TriangleMeshVisual::updateLight(), modules.glmesh.meshvisual.MeshVisual::updateLight(), and modules.glmesh.meshvisual.MeshVisual::updateMesh().
update_impl()
virtual bool cie::gl::Scene::update_impl () protected pure virtual
Implementation-specific drawing.
Implemented in cie::gl::PartScene, cie::gl::Triangulated3DPartScene, cie::gl::GenericPartScene, and cie::gl::Axes3DScene.
vertexShader()
const Shader::SharedPointer& cie::gl::Scene::vertexShader () const
Member Data Documentation
_activeSceneID
Size cie::gl::Scene::_activeSceneID static protected
_cameras
camera_container cie::gl::Scene::_cameras protected
_p_bufferManager
BufferManager::SharedPointer cie::gl::Scene::_p_bufferManager protected
_p_fragmentShader
Shader::SharedPointer cie::gl::Scene::_p_fragmentShader protected
_p_geometryShader
Shader::SharedPointer cie::gl::Scene::_p_geometryShader protected
_p_vertexShader
Shader::SharedPointer cie::gl::Scene::_p_vertexShader protected
_textures
texture_container cie::gl::Scene::_textures protected
Referenced by modules.gltexture.texture.AggregatedTexture::__init__(), modules.gltexture.texture.AggregatedTexture::build(), and modules.gltexture.texture.AggregatedTexture::registerTexture().
_uniforms
uniform_container cie::gl::Scene::_uniforms protected
_vaoID
GLuint cie::gl::Scene::_vaoID protected
The documentation for this class was generated from the following file:
Scene.hpp