ciegl: cie::gl::AbsProgram Class Reference
cie::gl::AbsProgram Class Reference abstract
Classes
class ActiveContextToken
A class that disables the program that constructed it upon destruction.
Public Member Functions
AbsProgram (AbsProgram &&r_rhs)=default
virtual ~AbsProgram ()
virtual void update ()=0
ActiveContextToken activate (bool log=false)
bool isActive ()
Public Member Functions inherited from cie::utils::Loggee
Loggee (Logger &r_logger, const std::string &r_instanceName)
~Loggee ()
void log (const std::string &message, size_t messageType=LOG_TYPE_MESSAGE)
void logID (const std::string &message, size_t id, size_t messageType=LOG_TYPE_MESSAGE)
size_t tic ()
void toc (size_t timerID, bool reset=true)
void toc (const std::string &message, size_t timerID, bool reset=true)
LogBlock newBlock (const std::string &r_name)
void separate ()
Public Member Functions inherited from cie::utils::NamedObject
NamedObject (std::string &&r_name)
NamedObject (const std::string &r_name)
NamedObject (NamedObject &&r_rhs)=default
NamedObject (const NamedObject &r_rhs)=default
NamedObject & operator= (NamedObject &&r_rhs)=default
NamedObject & operator= (const NamedObject &r_rhs)=default
const std::string & name () const
void setName (const std::string &r_name)
virtual void setName (std::string::const_iterator begin, std::string::const_iterator end)
virtual ~NamedObject ()
Public Member Functions inherited from cie::utils::IDObject< class >
IDObject ()
IDObject (const TID &r_id)
IDObject (IDObject &&r_rhs)=default
IDObject (const IDObject &r_rhs)=default
IDObject & operator= (IDObject &&r_rhs)=default
IDObject & operator= (const IDObject &rhs)=default
void setID (TID id)
const TID getID () const
Protected Member Functions
AbsProgram ()
AbsProgram (utils::Logger &r_logger, const std::string &r_name="Program")
void link ()
virtual void deactivate (bool log=false)
This doesn't do anything except log a request to disable the program.
BufferManager & getBufferManager ()
const BufferManager & getBufferManager () const
std::string getErrorString () const
Protected Member Functions inherited from cie::utils::Loggee
Logger & logger ()
Additional Inherited Members
Public Types inherited from cie::utils::IDObject< class >
typedef TID id_type
Protected Attributes inherited from cie::utils::IDObject< class >
TID _id
Constructor & Destructor Documentation
AbsProgram() [1/3]
cie::gl::AbsProgram::AbsProgram (AbsProgram && r_rhs) default
~AbsProgram()
virtual cie::gl::AbsProgram::~AbsProgram () virtual
AbsProgram() [2/3]
cie::gl::AbsProgram::AbsProgram () protected
AbsProgram() [3/3]
cie::gl::AbsProgram::AbsProgram (utils::Logger & r_logger, const std::string & r_name = "Program") protected
Member Function Documentation
activate()
ActiveContextToken cie::gl::AbsProgram::activate (bool log = false)
deactivate()
virtual void cie::gl::AbsProgram::deactivate (bool log = false) protected virtual
This doesn't do anything except log a request to disable the program.
getBufferManager() [1/2]
BufferManager& cie::gl::AbsProgram::getBufferManager () protected
getBufferManager() [2/2]
const BufferManager& cie::gl::AbsProgram::getBufferManager () const protected
getErrorString()
std::string cie::gl::AbsProgram::getErrorString () const protected
isActive()
bool cie::gl::AbsProgram::isActive ()
link()
void cie::gl::AbsProgram::link () protected
update()
virtual void cie::gl::AbsProgram::update () pure virtual
Referenced by modules.glvisuals.linevisual.LineVisual::highlightMarkers(), modules.glvisuals.markervisual.MarkerVisual::highlightMarkers(), modules.lighting.timedlight.TimedSpotLight::on_timer(), modules.glmesh.meshvisual.TriangleMeshVisual::updateLight(), modules.glmesh.meshvisual.MeshVisual::updateLight(), and modules.glmesh.meshvisual.MeshVisual::updateMesh().
The documentation for this class was generated from the following file:
AbsProgram.hpp