ciegl: cie::gl::AbsCamera Class Reference
cie::gl::AbsCamera Class Reference abstract
Public Types
using internal_matrix_type = glm::mat4
using internal_vector_type = glm::vec4
using external_vector_type = glm::dvec3
Public Types inherited from cie::gl::RigidBody
using vector_type = glm::dvec3
using quaternion_type = glm::dquat
using matrix_type = glm::dmat4
Public Member Functions
AbsCamera (utils::Logger &r_logger=utils::LoggerSingleton::get(), const std::string &r_name="AbsCamera", const AbsCamera::vector_type &r_position={0.0, 0.0, 1.0}, const AbsCamera::vector_type &r_direction={0.0, 0.0, -1.0}, const AbsCamera::vector_type &r_up={0.0, 1.0, 0.0})
AbsCamera (const AbsCamera &r_rhs)=default
AbsCamera (AbsCamera &&r_rhs)=default
AbsCamera & operator= (const AbsCamera &r_rhs)=delete
virtual void update ()
virtual void setPosition (const AbsCamera::vector_type &r_position) override
virtual void setPose (const AbsCamera::vector_type &r_position, const AbsCamera::vector_type &r_direction, const AbsCamera::vector_type &r_up) override
virtual void rotate (double radians, const AbsCamera::vector_type &r_axis) override
virtual void rotate (double radians, const AbsCamera::vector_type &r_axis, const AbsCamera::vector_type &r_pointOnAxis) override
const internal_matrix_type & viewMatrix () const
virtual const internal_matrix_type & projectionMatrix () const =0
const internal_matrix_type & transformationMatrix () const
virtual const std::pair< double, double > & clippingPlanes () const =0
virtual void setClippingPlanes (double nearClippingPlane, double farClippingPlane)=0
virtual void zoom (double scale)=0
virtual double aspectRatio () const =0
virtual void setAspectRatio (double aspectRatio)=0
virtual double fieldOfView () const =0
virtual void setFieldOfView (double radians)=0
Public Member Functions inherited from cie::utils::Loggee
Loggee (Logger &r_logger, const std::string &r_instanceName)
~Loggee ()
void log (const std::string &message, size_t messageType=LOG_TYPE_MESSAGE)
void logID (const std::string &message, size_t id, size_t messageType=LOG_TYPE_MESSAGE)
size_t tic ()
void toc (size_t timerID, bool reset=true)
void toc (const std::string &message, size_t timerID, bool reset=true)
LogBlock newBlock (const std::string &r_name)
void separate ()
Public Member Functions inherited from cie::utils::NamedObject
NamedObject (std::string &&r_name)
NamedObject (const std::string &r_name)
NamedObject (NamedObject &&r_rhs)=default
NamedObject (const NamedObject &r_rhs)=default
NamedObject & operator= (NamedObject &&r_rhs)=default
NamedObject & operator= (const NamedObject &r_rhs)=default
const std::string & name () const
void setName (const std::string &r_name)
virtual void setName (std::string::const_iterator begin, std::string::const_iterator end)
virtual ~NamedObject ()
Public Member Functions inherited from cie::gl::RigidBody
RigidBody (const vector_type &r_position, const vector_type &r_direction, const vector_type &r_up)
RigidBody ()
RigidBody (const RigidBody &r_rhs)=default
RigidBody (RigidBody &&r_rhs)=default
const vector_type & position () const
const vector_type & direction () const
const vector_type & up () const
virtual void translate (const vector_type &r_translation)
Translate body by the specified vector.
void rotateYaw (double radians)
Rotate body around its local z axis.
void rotatePitch (double radians)
Rotate body around its local y axis.
void rotateRoll (double radians)
Rotate body around its local x axis.
vector_type getLocalXAxis () const
Roll axis.
vector_type getLocalYAxis () const
Pitch axis.
vector_type getLocalZAxis () const
Yaw axis.
Protected Member Functions
virtual void rotateInPlace (double radians, const AbsCamera::vector_type &r_axis) override
void updateViewMatrix ()
virtual void updateProjectionMatrix ()=0
void updateTransformationMatrix ()
Protected Member Functions inherited from cie::utils::Loggee
Logger & logger ()
Protected Attributes
internal_matrix_type _viewMatrix
internal_matrix_type _transformationMatrix
Protected Attributes inherited from cie::gl::RigidBody
vector_type _position
vector_type _direction
vector_type _up
Detailed Description
Rigid body with view and transformation matrices
The projection matrix and its functionalities must be implemented by derived classes
Member Typedef Documentation
external_vector_type
using cie::gl::AbsCamera::external_vector_type = glm::dvec3
internal_matrix_type
using cie::gl::AbsCamera::internal_matrix_type = glm::mat4
internal_vector_type
using cie::gl::AbsCamera::internal_vector_type = glm::vec4
Constructor & Destructor Documentation
AbsCamera() [1/3]
cie::gl::AbsCamera::AbsCamera (utils::Logger & r_logger = utils::LoggerSingleton::get(), const std::string & r_name = "AbsCamera", const AbsCamera::vector_type & r_position = {0.0, 0.0, 1.0}, const AbsCamera::vector_type & r_direction = {0.0, 0.0, -1.0}, const AbsCamera::vector_type & r_up = {0.0, 1.0, 0.0})
AbsCamera() [2/3]
cie::gl::AbsCamera::AbsCamera (const AbsCamera & r_rhs) default
AbsCamera() [3/3]
cie::gl::AbsCamera::AbsCamera (AbsCamera && r_rhs) default
Member Function Documentation
aspectRatio()
virtual double cie::gl::AbsCamera::aspectRatio () const pure virtual
Implemented in cie::gl::Camera< ProjectionType >.
clippingPlanes()
virtual const std::pair<double,double>& cie::gl::AbsCamera::clippingPlanes () const pure virtual
Get near and far clipping planes
Implemented in cie::gl::Camera< ProjectionType >.
fieldOfView()
virtual double cie::gl::AbsCamera::fieldOfView () const pure virtual
Field of view in radians (vertical FoV)
Implemented in cie::gl::Camera< ProjectionType >.
operator=()
AbsCamera& cie::gl::AbsCamera::operator= (const AbsCamera & r_rhs) delete
projectionMatrix()
virtual const internal_matrix_type& cie::gl::AbsCamera::projectionMatrix () const pure virtual
Get up-to-date projection matrix
Implemented in cie::gl::Camera< ProjectionType >.
rotate() [1/2]
virtual void cie::gl::AbsCamera::rotate (double radians, const AbsCamera::vector_type & r_axis) override virtual
Rotate around axis going through the origin Trigger view and transformation matrix updates
Reimplemented from cie::gl::RigidBody.
rotate() [2/2]
virtual void cie::gl::AbsCamera::rotate (double radians, const AbsCamera::vector_type & r_axis, const AbsCamera::vector_type & r_pointOnAxis) override virtual
Rotate around an axis, Trigger view and transformation matrix updates
Reimplemented from cie::gl::RigidBody.
rotateInPlace()
virtual void cie::gl::AbsCamera::rotateInPlace (double radians, const AbsCamera::vector_type & r_axis) override protected virtual
Rotate around axis going through the camera Trigger view and transformation matrix updates
Reimplemented from cie::gl::RigidBody.
setAspectRatio()
virtual void cie::gl::AbsCamera::setAspectRatio (double aspectRatio) pure virtual
Set camera aspect ratio Trigger projection and transformation matrix updates
Implemented in cie::gl::Camera< ProjectionType >.
setClippingPlanes()
virtual void cie::gl::AbsCamera::setClippingPlanes (double nearClippingPlane, double farClippingPlane) pure virtual
Set near and far clipping planes Trigger projection and transformation matrix updates
Implemented in cie::gl::Camera< ProjectionType >.
setFieldOfView()
virtual void cie::gl::AbsCamera::setFieldOfView (double radians) pure virtual
Field of view in radians (vertical FoV) Trigger projection and transformation matrix updates
Implemented in cie::gl::Camera< ProjectionType >.
setPose()
virtual void cie::gl::AbsCamera::setPose (const AbsCamera::vector_type & r_position, const AbsCamera::vector_type & r_direction, const AbsCamera::vector_type & r_up) override virtual
Set position and orientation Trigger view and transformation matrix updates
Reimplemented from cie::gl::RigidBody.
setPosition()
virtual void cie::gl::AbsCamera::setPosition (const AbsCamera::vector_type & r_position) override virtual
Set position Trigger view and transformation matrix updates
Reimplemented from cie::gl::RigidBody.
transformationMatrix()
const internal_matrix_type& cie::gl::AbsCamera::transformationMatrix () const
Get up-to-date transformation matrix
update()
virtual void cie::gl::AbsCamera::update () virtual
Update matrices By default, transformation matrices are kept up-to-date internally, but derived classes might need extra updating.
Referenced by modules.glvisuals.linevisual.LineVisual::highlightMarkers(), modules.glvisuals.markervisual.MarkerVisual::highlightMarkers(), modules.lighting.timedlight.TimedSpotLight::on_timer(), modules.glmesh.meshvisual.TriangleMeshVisual::updateLight(), modules.glmesh.meshvisual.MeshVisual::updateLight(), and modules.glmesh.meshvisual.MeshVisual::updateMesh().
updateProjectionMatrix()
virtual void cie::gl::AbsCamera::updateProjectionMatrix () protected pure virtual
Recompute projection matrix
Implemented in cie::gl::Camera< ProjectionType >.
updateTransformationMatrix()
void cie::gl::AbsCamera::updateTransformationMatrix () protected
Recompute transformation matrix Expects view and projection matrices to be up-to-date
updateViewMatrix()
void cie::gl::AbsCamera::updateViewMatrix () protected
Recompute view matrix
viewMatrix()
const internal_matrix_type& cie::gl::AbsCamera::viewMatrix () const
Get up-to-date view matrix
zoom()
virtual void cie::gl::AbsCamera::zoom (double scale) pure virtual
Camera type specific zooming Trigger projection and transformation matrix updates
Implemented in cie::gl::Camera< ProjectionType >.
Member Data Documentation
_transformationMatrix
internal_matrix_type cie::gl::AbsCamera::_transformationMatrix protected
_viewMatrix
internal_matrix_type cie::gl::AbsCamera::_viewMatrix protected
The documentation for this class was generated from the following file:
AbsCamera.hpp