ciegl: cie::gl::AbsPlot Class Reference
cie::gl::AbsPlot Class Reference abstract
Public Member Functions
AbsPlot (AbsWindow::SharedPointer p_window)
AbsPlot ()
virtual void update ()
virtual void fit (bool keepAspectRatio=false)=0
void show ()
const AttributeContainer & attributes () const
Protected Attributes
AbsWindow::SharedPointer _p_window
AttributeContainer::SharedPointer _p_attributes
Constructor & Destructor Documentation
AbsPlot() [1/2]
cie::gl::AbsPlot::AbsPlot (AbsWindow::SharedPointer p_window)
AbsPlot() [2/2]
cie::gl::AbsPlot::AbsPlot ()
Member Function Documentation
attributes()
const AttributeContainer& cie::gl::AbsPlot::attributes () const
fit()
virtual void cie::gl::AbsPlot::fit (bool keepAspectRatio = false) pure virtual
Implemented in cie::gl::AbsPlot2< Tag, Args >, cie::gl::AbsPlot2< std::true_type >, and cie::gl::AbsPlot2< std::false_type, Args... >.
show()
void cie::gl::AbsPlot::show ()
update()
virtual void cie::gl::AbsPlot::update () virtual
Referenced by modules.glvisuals.linevisual.LineVisual::highlightMarkers(), modules.glvisuals.markervisual.MarkerVisual::highlightMarkers(), modules.lighting.timedlight.TimedSpotLight::on_timer(), modules.glmesh.meshvisual.TriangleMeshVisual::updateLight(), modules.glmesh.meshvisual.MeshVisual::updateLight(), and modules.glmesh.meshvisual.MeshVisual::updateMesh().
Member Data Documentation
_p_attributes
AttributeContainer::SharedPointer cie::gl::AbsPlot::_p_attributes protected
_p_window
AbsWindow::SharedPointer cie::gl::AbsPlot::_p_window protected
The documentation for this class was generated from the following file:
AbsPlot.hpp